---
# tasks file for vim
- name: -基础依赖安装--
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - ctags
    - ncurses
    - ncurses-devel
    - gcc
    - gcc-c++
    - readline-devel
    - bzip2
    - openssl
    - openssl-devel
    - 'zlib*'
    - libffi-devel
    - python-devel


- name: 下载Cmake
  unarchive:
    src: https://cmake.org/files/v3.12/cmake-3.12.0.tar.gz
    dest: /tmp
    remote_src: yes
- name: 安装Cmake
  shell: "cd cmake-3.12.0 && ./bootstrap && make && make install"
  args:
    chdir: /tmp

- name: 下载Python3.7版本
  unarchive:
    src: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz
    dest: /tmp
    remote_src: yes

- name: 安装Python3.7
  shell: "cd Python-3.7.0 && ./configure && make && make install"
  args:
    chdir: /tmp
- name: 安装Jedi
  shell: pip3.7 install jedi && pip2.7 install jedi

- name: 下载lua5.3.5版本
  unarchive:
    src: http://www.lua.org/ftp/lua-5.3.5.tar.gz
    dest: /tmp
    remote_src: yes

- name: 安装lua5.3.5
  shell: "cd lua-5.3.5 && make linux test && make install"
  args:
    chdir: /tmp

- name: 准备vim环境
  unarchive:
    src: ftp://ftp.vim.org/pub/vim/unix/vim-8.1.tar.bz2
    dest: /tmp
    remote_src: yes

- name: 安装vim
  shell: "cd vim81 && ./configure --with-features=huge --enable-multibyte --with-ruby-command=ruby   --enable-pythoninterp=yes --enable-gui=gtk2 --enable-cscope --enable-luainterp --with-lua-prefix=/usr/local --with-python-config-dir=/usr/lib64/python2.7/config --enable-fontset --enable-rubyinterp=dynamic --enable-perlinterp=yes --enable-python3interp=yes --with-python3-config-dir=/usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu && make && make install"
  args:
    chdir: /tmp

- name: -安装powerline字体-
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: /opt/checkout
    version: master
    clone: yes
    update: yes
- name: -安装fronts字体文件-
  shell: sh install.sh
  args:
    chdir: /opt/checkout
- name: -安装vim 插件管理器-
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim
    version: master
    clone: yes
    update: yes
- name: -安装vim_fugitive插件-
  git:
    repo: 'https://github.com/tpope/vim-fugitive.git'
    dest: ~/.vim/bundle/vim-fugitive
    version: master
    clone: yes
    update: yes
- name: -安装Molokai color scheme for vim-
  git:
    repo: 'https://github.com/tomasr/molokai.git'
    dest: ~/.vim/colors
    version: master
    clone: yes
- name: -字体主题插件拷贝-
  copy:
    src: ~/.vim/colors/colors/molokai.vim
    dest: ~/.vim/colors/molokai.vim

- name: -下载fuzzy finder-
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: ~/.fzf
    version: master
    clone: yes
- name: -安装fuzzy finder-
  shell: ./install --all
  args:
    chdir: ~/.fzf
    executable: /bin/bash
- name: -拷贝vimrc模板文件-
  template:
    src: vimrc.j2
    dest: ~/.vimrc
    mode: u=rw,g=r,o=r
- name: 初始化vimrc配置文件
  shell: vim +PluginInstall +qall
- name: 安装YouCompleteMe插件
  shell: git submodule update --init --recursive && ./install.sh --clang-completer
  args:
    chdir: ~/.vim/bundle/YouCompleteMe
